### ISSUE TITLE
TypeError: Cannot read property 'toJSON' of null while adding a new record

### ISSUE THREAD

**Issue by davidnge** [SoftwareBrothers/admin-bro#167] opened 2019-10-10 20:17 UTC
I have set up the admin panel via sequelizejs adapter, and the database I'm using is postgresql.

The admin panel is working and the data is loaded, [screenshot here for ref](https://www.dropbox.com/s/nzpb7evctbda5c9/Screenshot%202019-10-10%2022.07.49.png?dl=0).

The problem arise when I try to add a new record/row to the table using the admin UI. 

I receive the following error after I press "save":

```
Executing (default): UPDATE "tag" SET "name"=$1,"id"=$2,"updatedAt"=$3 WHERE "id" = $4
Executing (default): SELECT "id", "name", "createdAt", "updatedAt" FROM "tag" AS "tag" WHERE "tag"."id" = '72';
TypeError: Cannot read property 'toJSON' of null
    at Resource.update (/Users/davidnge/Desktop/remote-frontend/node_modules/admin-bro-sequelizejs/src/resource.js:126:21)
```

**Note:** I receive this error for every single table I try adding a new row/record. I am able to edit the existing record just fyi.

Is this a known issue? 

Appreciate any idea to resolve this. Let me know if there's other info you need from me.

thanks in advance!

**Comment by wojtek-krysiak** [comment] 2019-10-11 20:34
can you write a schema for your Tag model? - I will try to recreate this locally.
and please write admin-bro and admin-bro-sequelize versions

**Comment by davidnge** [comment] 2019-10-11 21:21
Here's my code under /models folder  (using sequelizejs)

```
//   /models/tags.js

module.exports = (sequelize, type) => {
    return sequelize.define('tag', {
        id: {
          type: type.INTEGER,
          primaryKey: true,
          autoIncrement: true
        },
        name: {type:type.STRING, allowNull: true, unique:true}
    }, 
    {
      freezeTableName: true
    })
}


//    /models/job.js

module.exports = (sequelize, type) => {
    return sequelize.define('job', {
        id: {
          type: type.STRING,
          primaryKey: true,
          autoIncrement: false
        },
        title: {type:type.STRING, allowNull: true},
        url: {type:type.STRING, allowNull: true, unique: true},
        location: {type:type.STRING, allowNull: true},
        date: {type:type.STRING, allowNull: true},
        jobDescription: {type:type.TEXT, allowNull: true},
    }, 
    {
      freezeTableName: true
    })
}


//    /models/index.js

const JobModel = require('./job');
const TagModel = require('./tag');
const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');

const db = {}

const sequelize = new Sequelize('db', 'test', 'test', {
    host: 'localhost',
    dialect: 'postgres',
  })

const JobTag = sequelize.define('job_tag', {}, {freezeTableName: true})
const Job = JobModel(sequelize, Sequelize)
const Tag = TagModel(sequelize, Sequelize)

Job.belongsToMany(Tag, { through: JobTag, unique: false });
Tag.belongsToMany(Job, { through: JobTag, unique: false });

fs
    .readdirSync(__dirname)
    .filter((file) =>{
        file !== "index.js"
    }) 
    .forEach((file) => {
        const model = sequelize.import(path.join(__dirname, file))
        db[model.name] = model
    })

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = {
    db
  }
```

I'm currently using
admin-bro: v1.2.0
admin-bro-expressjs: v0.2.0,
admin-bro-sequelizejs": v0.2.6

thanks for looking into this! Let me know if you need other info.

**Comment by dustin-rcg** [comment] 2019-10-23 12:28
I was seeing a similar error message. If I supplied a value for the ID field of the new record (which I only did for testing), then I would see the same `UPDATE` error @davidnge wrote. Otherwise, AdminBro would show the error "There were errors in the record object. Check them out", but nothing else was logged anywhere for me to check. I just started commenting out fields in my Sequelize model until I found the problem. It seems to have been caused by an improperly mapped field in my Sequelize model. I had
```
sequelize.define('principal', {
...
commonName : { type: DataTypes.STRING, allowNull: false, field: "common_name" }
...
})
```
and it seems the value for `commonName` property was not being transferred to `common_name` database column. When I commented out that field in the Sequelize model, then finally no error in AdminBro UI and an `INSERT` was issued in the console (but of course failed due to the property being required).  I then changed that property definition to
```
common_name : { type: DataTypes.STRING, allowNull: false }
```
and the problem went away.  I don't know if this is a Sequelize problem or an AdminBro problem.

That doesn't seem to be exactly @davidnge 's problem on the `tag` entity, but maybe is related somehow.

**Comment by wojtek-krysiak** [comment] 2019-12-21 10:52
I think that the job model is a problem. You set the primary key to be a string and you turn off the autoincrement.

So when AdminBro tries to create a new record he is not passing id via params because he assumes that id field will be autoincremented by sequelize.

To solve that you can set defaultValue in sequelize to UUID or something else (depending on your requirements)

**Closed by wojtek-krysiak** 2019-12-21 10:52 UTC
