### ISSUE TITLE
Demo website not working

### ISSUE THREAD

**Issue by VitDev17** [SoftwareBrothers/admin-bro#722] opened 2020-12-23 22:55 UTC
The demo page for the admin-bro app is not accessible

**To Reproduce**
1. Go to Admin Bro github page and click on the see demo button

**Expected behavior**
Demo to be opened

**Comment by hansfpc** [comment] 2021-01-05 21:13
same problem here

**Comment by gmwill934** [comment] 2021-01-19 04:23
same problem here, how can we help?

**Comment by SimonB407** [comment] 2021-01-26 15:23
Duplicate of #684

**Closed by SimonB407** 2021-01-26 15:23 UTC
