### ISSUE TITLE
I have a question about the login page.

### ISSUE THREAD

**Issue by kir931028** [SoftwareBrothers/admin-bro#531] opened 2020-07-27 01:20 UTC
I knew I could change the text on the login page. This is so amazing!
But is there any way to remove or change the bg image of the login page?
I'll wait for the answer :)

**Comment by wojtek-krysiak** [comment] 2020-07-27 12:46
not in an easy way - you will need to write your own logic for login which will require:

* using buildRouter instead of buildAuthenticatedRouter
* writing your custom routes for login (take a look at the source code for buildAuthenticatedRouter)
* this routes should render login page (you can render whatever you like
* and you have to write current user to `req.session.adminUser`

**Comment by kir931028** [comment] 2020-07-28 02:14
Your answer helped me so much.
We hope to be able to change the image of the login banner as soon as possible.
I am using Admin-bro very well.
Thank you.

**Comment by morfeii** [comment] 2020-09-22 18:41
@kir931028 Did you manage to change the image of the login page?

**Comment by kir931028** [comment] 2020-09-23 01:25
@morfeii No... I couldn't find a way to erase it, so I just edited it to erase the text.

**Comment by ayushbhat** [comment] 2020-10-16 05:14
@kir931028 Hi, can you tell what file did you edit to change the text?

**Comment by morfeii** [comment] 2020-10-17 09:46
@kir931028 property "locale" in options. for example: 
```
const options = {
  resources: [ ],
  branding: { },
  locale: {
    translations: {
      messages: {
        loginWelcome: 'Blablabla'
      },
    }
  },
};
```

**Comment by kir931028** [comment] 2020-10-21 01:43
@ayushbhat I did the same as @morfeii comment

**Comment by SimonB407** [comment] 2021-01-26 15:33
Duplicate of #347

**Closed by SimonB407** 2021-01-26 15:33 UTC
