### ISSUE TITLE
Avatar should be changable

### ISSUE THREAD

**Issue by genp** [SoftwareBrothers/admin-bro#338] opened 2020-02-29 17:38 UTC
In the `LoggedUser` component, the `email` is a prop but the displayed avatar image is hard coded:
```
<img src="https://api.adorable.io/avatars/24/softwarebrothers.png" alt="avatar" />
```

Can you update the image src to come from a prop as well?

**Comment by genp** [comment] 2020-02-29 17:44
This may be a duplicate of #329

**Comment by wojtek-krysiak** [comment] 2020-02-29 19:20
yep it is duplicate of #329 - will be closed soon.

**Closed by wojtek-krysiak** 2020-02-29 19:20 UTC
