### ISSUE TITLE
express-formidable required but not in the docs?

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [SoftwareBrothers/admin-bro#432] opened 2020-05-01 14:08 UTC
First, THANK YOU! For Admin Bro. This is going to save us a massive amount of time!

**Describe the bug**
Followed the instructions here: https://adminbro.com/tutorial-installation-instructions.html and here: https://adminbro.com/module-admin-bro-sequelizejs.html

**Installed libraries and their versions**

* admin-bro@2.2.12
* admin-bro-expressjs@2.0.5
* admin-bro-sequelizejs@0.4.1
* swagger-jsdoc@4.0.0 <-- maybe a conflict?

**To Reproduce**
1. Not really sure. My best guess is that "express-formidable" is required or there is some sort of conflict with "swagger-jsdoc"

**Additional context**
```yarn add express-formidable``` fixed the issue. Nothing needs to be fixed as best I can tell other than maybe an update to the docs or maybe just closing this bug report and letting anyone who runs into this issue can search for this bug report. Once we added express-formidable everything worked as expected.

**Stack Trace**
```
Successfully built 2bff43b33207
Successfully tagged reporter:devLocal
Recreating reporter_Reporter_1 ... done
Attaching to reporter_Reporter_1
Reporter_1  | internal/modules/cjs/loader.js:716
Reporter_1  |     throw err;
Reporter_1  |     ^
Reporter_1  |
Reporter_1  | Error: Cannot find module 'express-formidable'
Reporter_1  | Require stack:
Reporter_1  | - /usr/src/app/node_modules/admin-bro-expressjs/plugin.js
Reporter_1  | - /usr/src/app/node_modules/admin-bro-expressjs/index.js
Reporter_1  | - /usr/src/app/src/index.js
Reporter_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
Reporter_1  |     at Function.Module._load (internal/modules/cjs/loader.js:618:27)
Reporter_1  |     at Module.require (internal/modules/cjs/loader.js:771:19)
Reporter_1  |     at require (internal/modules/cjs/helpers.js:68:18)
Reporter_1  |     at Object.<anonymous> (/usr/src/app/node_modules/admin-bro-expressjs/plugin.js:5:30)
Reporter_1  |     at Module._compile (internal/modules/cjs/loader.js:868:30)
Reporter_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
Reporter_1  |     at Module.load (internal/modules/cjs/loader.js:731:32)
Reporter_1  |     at Function.Module._load (internal/modules/cjs/loader.js:644:12)
Reporter_1  |     at Module.require (internal/modules/cjs/loader.js:771:19) {
Reporter_1  |   code: 'MODULE_NOT_FOUND',
Reporter_1  |   requireStack: [
Reporter_1  |     '/usr/src/app/node_modules/admin-bro-expressjs/plugin.js',
Reporter_1  |     '/usr/src/app/node_modules/admin-bro-expressjs/index.js',
Reporter_1  |     '/usr/src/app/src/index.js'
Reporter_1  |   ]
Reporter_1  | }
reporter_Reporter_1 exited with code 1
```

edit: grammar

**Comment by wojtek-krysiak** [comment] 2020-05-01 23:00
glad you liked it. We are working on it all the time so in case of any problems/errors feel free to ask me on our slack channel (you can get there from adminbro.com).

So just to confirm: the problem is only with missing dependency `express-formidable` and you fixed by installing it?

I see that it might not be clear after reading the docs one more time. We put info about it [there](https://adminbro.com/module-admin-bro-expressjs.html), but not [there](https://adminbro.com/tutorial-installation-instructions.html).

I will fix that right away.

Also if you spot any missing information in the docs - please create an issue.

**Comment by wojtek-krysiak** [comment] 2020-05-01 23:09
and fixed. Thanks again

**Closed by wojtek-krysiak** 2020-05-01 23:09 UTC
