### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by al6x** [SoftwareBrothers/admin-bro#701] opened 2020-12-04 23:11 UTC
<img width="1002" alt="Screen Shot 2020-12-05 at 2 11 05 am" src="https://user-images.githubusercontent.com/94196/101224270-2b5ac100-369f-11eb-93fe-c25f51aa4d39.png">

**Comment by fogine** [comment] 2020-12-10 12:08
its been migrated to 
https://admin-bro-app.firebaseapp.com/admin

**Comment by al6x** [comment] 2020-12-14 06:01
Thanks, is the password the same? The `test@example.com/password` is not working.

**Comment by fogine** [comment] 2020-12-14 09:09
I think its admin@example.com

**Comment by jligeza** [comment] 2020-12-22 09:52
@fogine admin@example.com:password doesn't work

**Comment by fogine** [comment] 2020-12-28 09:03
it did, now it doesnt :(

**Comment by SimonB407** [comment] 2021-01-26 15:23
Duplicate of #684

**Closed by SimonB407** 2021-01-26 15:23 UTC
Labels: duplicate
