### ISSUE TITLE
Admin page not loading correctly

### ISSUE THREAD

**Issue by pmourad** [SoftwareBrothers/admin-bro#193] opened 2019-11-01 14:37 UTC
Hi! The pages are not loading correctly. I don't know if it's a bug. The input fields and tables are not showing at all. Here are some screen shots of how the page looks and what the console shows.  

![Screen Shot 2019-11-01 at 11 27 15](https://user-images.githubusercontent.com/8883090/68032178-ed20f000-fc9b-11e9-9b31-5e1a280f49b0.png)

![Screen Shot 2019-11-01 at 11 36 56](https://user-images.githubusercontent.com/8883090/68032182-ef834a00-fc9b-11e9-81fd-f4b1f9820a4c.png)

**Comment by bartekczyz** [comment] 2019-11-01 15:02
@pmourad duplicate of #192

**Closed by bartekczyz** 2019-11-01 15:02 UTC
