### ISSUE TITLE
Unhandled type: Array

### ISSUE THREAD

**Issue by derkweijers** [SoftwareBrothers/admin-bro#90] opened 2019-05-21 08:54 UTC
I have a couple of properties in my mongoose model that are Arrays. Right now, I get a lot of warnings: `Unhandled type: Array`. I'm not sure if I missed something in the configuration or if the way I use arrays are not supported (yet).

Example from the model:
ArrayOfNumbers: [Number]

**Comment by wojtek-krysiak** [comment] 2019-05-21 10:56
arrays are not supported (yet) - you have to override this property in resource options. But let's leave this issue - we will be implementing this in the following weeks probably

**Comment by anurupr** [comment] 2019-06-25 03:11
can you explain how to override this property? I'm using the same configuration for another project (rest-hapi to be specific) . i don't mind using a workaround till it is implemented.

**Comment by DyaryRaoof** [comment] 2019-08-15 11:10
having the same issue. its been 2 month since the last post that anurupr wrote and i am still getting the same error

**Comment by derkweijers** [comment] 2019-08-15 11:13
Apologies for my late response. For now I've decided to go with Keystone since this was blocking for me and I didn't had the time to write my own component. Hope this will be fixed in the future so I can come back.

**Comment by anurupr** [comment] 2019-08-15 11:24
i was able to modify the core to handle arrays and it did work for my use case but not sure if it is production ready. i think with sufficient testing , it can be made that way. i can have a fork ready in a day or two. quite held up at the moment

**Comment by ekrmh** [comment] 2019-08-18 19:50
Is there an development in the issue?

**Comment by wojtek-krysiak** [comment] 2019-08-23 18:21
yes - I am working on it right now

**Comment by wojtek-krysiak** [comment] 2019-08-25 18:51
I am happy to announce that arrays support for mongoose adapter was added in AdminBro v1.1.0 with AdminBroMongoose v0.3.0

**Comment by DyaryRaoof** [comment] 2019-08-25 20:00
Thank you @wojtek-krysiak . Admin-bro is terrific. Is there a plan for adding support for objects with multiple levels of nested variables ?

**Comment by wojtek-krysiak** [comment] 2019-08-25 20:14
thanks! I also added nested schemas with version 1.1.0, so it should work.

**Comment by mopcweb** [comment] 2019-10-22 16:59
Hello, 

Thanks for awesome tool.

I managed to got into some trouble using this tool: 
![image](https://user-images.githubusercontent.com/40697120/67310298-2de37100-f506-11e9-8797-b52cb2cfe0ba.png)

![image](https://user-images.githubusercontent.com/40697120/67310461-74d16680-f506-11e9-81f4-bd2f16aa9de6.png)

There is no opportunity to use Array or Object type in schema. 

Is there any plans for providing this functionality ?

Thanks

**Comment by sharath-mallikarjuna** [comment] 2020-04-26 18:38
Hi @wojtek-krysiak 
Is there a fix for the above issue of handling Arrays and Objects?
The issue is still persists in the latest version

**Comment by sharath-mallikarjuna** [comment] 2020-04-29 16:25
Hi @wojtek-krysiak 
I've got this fixed by defining the schema in a right way as mentioned here
https://github.com/SoftwareBrothers/admin-bro-example-app/blob/master/mongoose/complicated-model.js 
And it works perfectly. Thank you :)

**Closed** 2020-04-29 18:25 UTC
